//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CariHesaplar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CariHesaplar()
        {
            this.CARI_HESAP_HAREKETLERI = new HashSet<CARI_HESAP_HAREKETLERI>();
        }
    
        public int CariHesapID { get; set; }
        public string CariKodu { get; set; }
        public string Unvan { get; set; }
        public string VergiNumarasi { get; set; }
        public string VergiDairesi { get; set; }
        public string Telefon { get; set; }
        public string Adres { get; set; }
        public Nullable<int> TedarikciID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CARI_HESAP_HAREKETLERI> CARI_HESAP_HAREKETLERI { get; set; }
        public virtual Tedarikci Tedarikci { get; set; }
    }
}
